/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // ── Token lama (dipakai di halaman-halaman selain Login) ──
        laut: {
          DEFAULT: '#1E6091',
          dark: '#154A70',
        },
        pasir: '#FDF6EC',
        karang: {
          DEFAULT: '#F4A261',
          dark: '#E08B3F',
        },

        // ── Token Material 3 dari desain Stitch (dipakai Login & halaman baru) ──
        'surface-container-high': '#eee7dd',
        'on-primary-fixed-variant': '#004a77',
        'on-tertiary-container': '#94e7b0',
        'secondary-container': '#ffab69',
        outline: '#717880',
        tertiary: '#00502c',
        'tertiary-fixed': '#a1f5bc',
        'primary-container': '#1e6091',
        'on-tertiary-fixed': '#00210f',
        'tertiary-container': '#0e6a3e',
        'on-primary-fixed': '#001d33',
        secondary: '#8e4e14',
        primary: '#004873',
        'on-tertiary': '#ffffff',
        'secondary-fixed-dim': '#ffb780',
        'secondary-fixed': '#ffdcc4',
        'on-surface-variant': '#41474f',
        'on-primary-container': '#b5d9ff',
        'surface-container': '#f4ede3',
        'outline-variant': '#c1c7d0',
        'inverse-on-surface': '#f7f0e6',
        'inverse-primary': '#97cbff',
        'on-secondary': '#ffffff',
        'on-error-container': '#93000a',
        'surface-variant': '#e8e2d8',
        'on-secondary-fixed': '#2f1400',
        background: '#fff8f0',
        'surface-dim': '#e0d9d0',
        'surface-container-lowest': '#ffffff',
        'tertiary-fixed-dim': '#85d8a2',
        'surface-tint': '#216293',
        'on-error': '#ffffff',
        'on-primary': '#ffffff',
        'surface-container-highest': '#e8e2d8',
        'surface-container-low': '#faf3e9',
        'primary-fixed': '#cee5ff',
        surface: '#fff8f0',
        'primary-fixed-dim': '#97cbff',
        'on-tertiary-fixed-variant': '#00522d',
        'on-background': '#1e1b16',
        'error-container': '#ffdad6',
        'inverse-surface': '#33302a',
        'on-secondary-container': '#783d01',
        error: '#ba1a1a',
        'surface-bright': '#fff8f0',
        'on-surface': '#1e1b16',
        'on-secondary-fixed-variant': '#6f3800',
        'coral-orange': '#F4A261',
        'sea-blue': '#1E6091',
      },
      borderRadius: {
        card: '20px',
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1.25rem',
        full: '9999px',
      },
      spacing: {
        'section-gap': '40px',
        'stack-sm': '8px',
        'stack-md': '16px',
        gutter: '16px',
        'stack-lg': '24px',
        'container-margin': '20px',
      },
      fontFamily: {
        'headline-md': ['Inter'],
        'title-lg': ['Inter'],
        'body-lg': ['Inter'],
        'display-lg-mobile': ['Inter'],
        'display-lg': ['Inter'],
        'body-md': ['Inter'],
        'label-md': ['Inter'],
      },
      fontSize: {
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'title-lg': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'display-lg-mobile': ['28px', { lineHeight: '36px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'display-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'label-md': ['12px', { lineHeight: '16px', fontWeight: '500' }],
      },
    },
  },
  plugins: [],
};
